spring.application.name=myhomepage

# DB説接続URL
spring.datasource.url=jdbc:mysql://localhost:3306/myhomepage

# DBユーザー名
spring.datasource.username=root

# DBパスワード
spring.datasource.password=admin

# SQLを表示
spring.jpa.show-sql=true

# DB自動更新
spring.jpa.hibernate.ddl-auto=update